# PyTorch Tensors Tutorial
Tensors are specialized data structures very similar to arrays and matrices. They encode model inputs, model outputs and model parameters. Tensors are similar to numpys ndarrays but can run on GPUs and other hardware. They can share the same underlying memory, therefore no need to copy data. Tensors are optimized for automatic differentiation.

Note: Differentiation is the process of finding the rate of change of a function with respect to one of its variables. In simpler terms, it calculates the slope of a function at a particular point. The result of differentiation is the derivative of the function. The derivative represents the function's rate of change at any given point and can also be thought of as the function's instantaneous rate of change.

In [2]:
import torch
import numpy as np

## Intializing a Tensor directly from data
Here the data is stored in a list of lists which results in a 2 x 2 tensor. The data type is automatically inferred as int64.

In [12]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.shape)
print(x_data.dtype)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64


In [13]:
data_f = [[1., 2.], [3., 4.]]
x_data_f = torch.tensor(data_f)
print(x_data_f)
print(x_data_f.shape)
print(x_data_f.dtype)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
torch.float32


## Intitalizing a Tensor from a numpy array

In [17]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(x_np.shape)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
torch.Size([2, 2])


In [18]:
np_array = np.array(data_f)
x_np = torch.from_numpy(np_array)
print(x_np)
print(x_np.shape)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
torch.Size([2, 2])


## Initalizing Tensor from another Tensor
The new tensor has the same properties (shape and datatype) as the first tensor unless explicitly overwritten.

In [21]:
x_ones = torch.ones_like(x_data)
print(x_ones)
print(x_ones.shape)
print(x_ones.dtype)

tensor([[1, 1],
        [1, 1]])
torch.Size([2, 2])
torch.int64


In [22]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)
print(x_rand.shape)
print(x_rand.dtype)

tensor([[0.5764, 0.1695],
        [0.3418, 0.8110]])
torch.Size([2, 2])
torch.float32


## Initialize Tensor from random or constant values
A tensor can be initialzed by defining the shape as a tuple and fill a tensor with given shape and constant values.

In [27]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(rand_tensor)
print(rand_tensor.shape)
print(rand_tensor.dtype)

tensor([[0.9414, 0.9954, 0.6404],
        [0.0100, 0.5657, 0.2297]])
torch.Size([2, 3])
torch.float32


In [28]:
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(ones_tensor.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


In [29]:
zero_tensor = torch.zeros(shape)
print(zero_tensor)
print(zero_tensor.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


## Attributes of Tensors
The tensor attributes describe the tensor shape and dtype. Furthermore they store the device the tensor is stored on. An important attribute for NN's is the grad attribute which is set to False by default.

In [33]:
print('Tensor shape:', ones_tensor.shape)
print('Tensor dtype:', ones_tensor.dtype)
print('Device where tensor is stored:', ones_tensor.device)
print('Tensor gradient:', ones_tensor.grad)

Tensor shape: torch.Size([2, 3])
Tensor dtype: torch.float32
Device where tensor is stored: cpu
Tensor gradient: None


In [35]:
ones_tensor = torch.ones(shape, requires_grad=True)
print(ones_tensor)
print(ones_tensor.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
None


## Operations on Tensors
A collection of all Tensor operations can be found here: https://pytorch.org/docs/stable/torch.html
Each operation can be conducted on GPU or CPU. CPU is used by default. Moving to GPU needs to be done explicitly.

In [40]:
# Slice and index Tensors
tensor = torch.zeros((3,5))
print('initialzed tensor with shape 3 x 5', tensor)
tensor[0,3] = 9.
print('Overwrite the 4th element in the first row:', tensor)
print('first row:', tensor[0])
print('4th column:', tensor[:,3])

initialzed tensor with shape 3 x 5 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Overwrite the 4th element in the first row: tensor([[0., 0., 0., 9., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
first row: tensor([0., 0., 0., 9., 0.])
4th column: tensor([9., 0., 0.])


In [43]:
# Concatenate tensors by adding columns
print('original tensor shape:', tensor.shape)
t1 = torch.cat([tensor, tensor], dim = 1)
print(t1)
print('t1 concatenated', t1.shape)

# Concatenate tensors by adding rows
t2 = torch.cat([tensor, tensor], dim = 0)
print(t2)
print('t2 concatenated', t2.shape)

original tensor shape: torch.Size([3, 5])
tensor([[0., 0., 0., 9., 0., 0., 0., 0., 9., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
t1 concatenated torch.Size([3, 10])
tensor([[0., 0., 0., 9., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 9., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
t2 concatenated torch.Size([6, 5])


In [50]:
# arithmetic operations
# matrix multiplication row dimension of first tensor must fit column dimension of second tensor
tensor = torch.ones((3, 5))
tensor[1,4] = 1
tensor[0,1] = 1
tensor[2,3] = 10
m = tensor @ tensor.T
print(m)
m1 = tensor.matmul(tensor.T)
m1


tensor([[  5.,   5.,  14.],
        [  5.,   5.,  14.],
        [ 14.,  14., 104.]])


tensor([[  5.,   5.,  14.],
        [  5.,   5.,  14.],
        [ 14.,  14., 104.]])

In [52]:
# element-wise product
z1 = tensor * tensor
print(z1)

z2 = tensor.mul(tensor)
z2

tensor([[  1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1., 100.,   1.]])


tensor([[  1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1., 100.,   1.]])

In [54]:
#element-wise addition
print(tensor + tensor)
print(tensor.add(tensor))

tensor([[ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2., 20.,  2.]])
tensor([[ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2., 20.,  2.]])


In [59]:
# aggregating a tensor into a single element tensor and getting the value
# summing
agg = tensor.sum()
print(agg)
print(agg.item())

# averaging
print(tensor.mean())
print(tensor.mean().item())

tensor(24.)
24.0
tensor(1.6000)
1.600000023841858


In [60]:
# inplace operations
print(tensor)
tensor.add_(4)
print(tensor)

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1., 10.,  1.]])
tensor([[ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5., 14.,  5.]])
